import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth title",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      Auth layout
      {children}
    </div>
  );
};

export default Layout;
