import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import s from "@/app/page.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SENIOR FRONTEND NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${s.main}`}>
        <div className={s.header}>
          <Link href="/">Main page</Link>
          <Link href="/posts">Posts</Link>
          <Link href="/login">Login</Link>
          <Link href="/signup">Sign up</Link>
          <Link href="/products">Products</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
