import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Specific products title",
  description: "Generated by create next app",
};
const Page = () => {
  return <div>Products page</div>;
};

export default Page;
